# Generated by Django 6.0.2 on 2026-03-04 22:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.horario'),
            preserve_default=False,
        ),
    ]
