# Generated by Django 6.0.2 on 2026-03-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_horario_remove_agendamento_hora_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horario',
            old_name='hora',
            new_name='horario',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
