# Generated by Django 6.0.2 on 2026-03-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_empresa_alter_agendamento_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='agenda.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.empresa'),
            preserve_default=False,
        ),
    ]
