# Generated by Django 6.0.2 on 2026-03-05 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_agendamento_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='agenda.empresa'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
