# Generated by Django 6.0.2 on 2026-03-05 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_agendamento_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-data', 'horario__horario', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['empresa__nome', 'horario']},
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horario',
            field=models.CharField(max_length=5),
        ),
        migrations.AddIndex(
            model_name='agendamento',
            index=models.Index(fields=['empresa', 'data', 'horario'], name='agenda_agen_empresa_7aa7b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='horario',
            constraint=models.UniqueConstraint(fields=('empresa', 'horario'), name='uniq_horario_por_empresa'),
        ),
    ]
